name: CI
on:
  push:
    branches: [ "main" ]

# GOALS:
# 1. Checkout and install python
# 2. Install dependencies (frozen-flask should install everything needed)
# 3. Freeze and zip and prepare for upload
# 3. Upload website build

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repo content
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install py dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r dependencies.txt
          FLASK_APP=python app.py build

      - name: Zip artifact
        run: |
          tar \
            --dereference --hard-dereference \
            --directory github-pages \
            --cvf github-pages \
            --exclude=.git \
            --exclude=.github \
            .


      - name: Upload build results
        uses: actions/upload-artifact@v3
        with:
          name: website
          path: github-pages