name: CI
on:
  push:
    branches: [ "main" ]

# GOALS:
# 1. Checkout and install python
# 2. Install dependencies (frozen-flask should install everything needed)
# 3. Freeze and zip and prepare for upload
# 3. Upload website build

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repo content
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install py dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r dependencies.txt
          python app.py build

      - name: Zip artifact
        uses: actions/upload-pages-artifact@v1
